/* ============================================================
   NESTORA — Data Layer
   All property, agent, development, testimonial and journal
   data lives here, separated from render/interaction logic.
   ============================================================ */

const IMG = (id, w = 1400) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

const NESTORA_PROPERTIES = [
  {
    id: "oak-residence",
    name: "The Oak Residence",
    location: "Jaipur, Rajasthan",
    area: "Amber Hills",
    price: 28500000,
    priceLabel: "₹2.85 Cr",
    listingType: "buy",
    type: "Villa",
    beds: 4,
    baths: 4,
    sqft: 3240,
    yearBuilt: 2024,
    parking: 2,
    floors: 2,
    status: "Ready to Move",
    furnished: "Semi-Furnished",
    featured: true,
    amenities: ["Private Pool", "Garden", "Smart Home", "Modular Kitchen", "Covered Parking", "Security", "Terrace", "Home Office"],
    tags: ["parking", "garden", "security"],
    images: [
      IMG("photo-1600585154340-be6161a56a0c"),
      IMG("photo-1600566753086-00f18fb6b3ea"),
      IMG("photo-1600607687939-ce8a6c25118c"),
      IMG("photo-1600210492486-724fe5c67fb0"),
      IMG("photo-1600585154526-990dced4db0d"),
    ],
    description:
      "Set behind a screen of mature neem trees in Amber Hills, The Oak Residence was designed around a single idea: that light should move through a home the way it moves through a courtyard. Long verandas trace the perimeter of the ground floor, drawing the outdoors in through every principal room. The material palette — local sandstone, teak, and lime-washed plaster — was chosen to age well against Jaipur's climate, not merely to photograph well on the day it was finished.",
    headline: "A home designed around light.",
    agentId: "aarav-mehta",
    walkscore: { city: 12, school: 8, airport: 15 },
    floorPlans: {
      "Ground Floor": IMG("photo-1503387762-592deb58ef4e", 1200),
      "First Floor": IMG("photo-1503387837-b154d5074bd2", 1200),
      "Rooftop": IMG("photo-1502005229762-cf1b2da7c5d6", 1200),
    },
  },
  {
    id: "casa-verde",
    name: "Casa Verde",
    location: "Goa",
    area: "Assagao",
    price: 42000000,
    priceLabel: "₹4.20 Cr",
    listingType: "buy",
    type: "Villa",
    beds: 5,
    baths: 5,
    sqft: 4850,
    yearBuilt: 2023,
    parking: 3,
    floors: 2,
    status: "Ready to Move",
    furnished: "Fully Furnished",
    featured: true,
    amenities: ["Private Pool", "Garden", "Smart Home", "Modular Kitchen", "Covered Parking", "Security", "Terrace", "Gym"],
    tags: ["pool", "garden", "parking", "gym"],
    images: [
      IMG("photo-1613490493576-7fde63acd811"),
      IMG("photo-1512917774080-9991f1c4c750"),
      IMG("photo-1616486338812-3dadae4b4ace"),
      IMG("photo-1560448204-e02f11c3d0e2"),
      IMG("photo-1521782462922-e78d0a35b8de"),
    ],
    description:
      "Casa Verde sits within a canopy of areca palm on the quiet edge of Assagao, five minutes from the village's cafés and studios. A double-height living pavilion opens fully on three sides to a 14-metre pool, blurring the line between built and unbuilt space. Upstairs, each of the five bedrooms has its own private balcony framed in reclaimed teak, looking out over paddy fields that flood green through the monsoon.",
    headline: "Where the garden and the house share one roof.",
    agentId: "mira-kapoor",
    walkscore: { city: 20, school: 11, airport: 35 },
    floorPlans: {
      "Ground Floor": IMG("photo-1503387762-592deb58ef4e", 1200),
      "First Floor": IMG("photo-1503387837-b154d5074bd2", 1200),
      "Rooftop": IMG("photo-1502005229762-cf1b2da7c5d6", 1200),
    },
  },
  {
    id: "terrace-house",
    name: "The Terrace House",
    location: "Mumbai",
    area: "Bandra West",
    price: 67500000,
    priceLabel: "₹6.75 Cr",
    listingType: "buy",
    type: "Penthouse",
    beds: 4,
    baths: 5,
    sqft: 3900,
    yearBuilt: 2022,
    parking: 2,
    floors: 1,
    status: "Ready to Move",
    furnished: "Fully Furnished",
    featured: true,
    amenities: ["Terrace", "Smart Home", "Modular Kitchen", "Covered Parking", "Security", "Home Office", "Gym"],
    tags: ["parking", "security", "gym"],
    images: [
      IMG("photo-1600607687644-aac4c3eac7f4"),
      IMG("photo-1560185127-6ed189bf02f4"),
      IMG("photo-1560449752-092c6a5db1f8"),
      IMG("photo-1600566752355-35792bedcfea"),
      IMG("photo-1600607688969-a5bfcd646154"),
    ],
    description:
      "Occupying the top floor of a low-rise residence in Bandra West, The Terrace House trades the vertical sprawl of a typical penthouse for a single continuous level, wrapped by 1,400 square feet of private terrace. Sea breeze reaches every room through pivoting steel-framed doors. The kitchen, finished in honed basalt, was built for a family that actually cooks — not for the listing photos.",
    headline: "The city below, the sky at your table.",
    agentId: "anaya-sharma",
    walkscore: { city: 6, school: 5, airport: 22 },
    floorPlans: {
      "Ground Floor": IMG("photo-1503387762-592deb58ef4e", 1200),
      "First Floor": IMG("photo-1503387837-b154d5074bd2", 1200),
      "Rooftop": IMG("photo-1502005229762-cf1b2da7c5d6", 1200),
    },
  },
  {
    id: "skyline-42",
    name: "Skyline 42",
    location: "Gurugram",
    area: "Golf Course Road",
    price: 39500000,
    priceLabel: "₹3.95 Cr",
    listingType: "buy",
    type: "Apartment",
    beds: 3,
    baths: 3,
    sqft: 2680,
    yearBuilt: 2025,
    parking: 2,
    floors: 1,
    status: "Ready to Move",
    furnished: "Unfurnished",
    featured: true,
    amenities: ["Gym", "Security", "Covered Parking", "Smart Home", "Modular Kitchen"],
    tags: ["parking", "gym", "security"],
    images: [
      IMG("photo-1600596542815-ffad4c1539a9"),
      IMG("photo-1600585154340-be6161a56a0c"),
      IMG("photo-1493809842364-78817add7ffb"),
      IMG("photo-1600210491892-03d54c0aaf87"),
      IMG("photo-1600121848594-d8644e57abab"),
    ],
    description:
      "On the 42nd floor above Golf Course Road, this apartment was fitted out with a restrained, almost architectural hand — book-matched stone, brushed brass hardware, and full-height glazing that keeps the Aravalli skyline as the room's only decoration. It's built for a couple who travel often and want a home that asks nothing of them when they return.",
    headline: "A quiet apartment above a loud city.",
    agentId: "kabir-singh",
    walkscore: { city: 9, school: 7, airport: 18 },
    floorPlans: {
      "Ground Floor": IMG("photo-1503387762-592deb58ef4e", 1200),
      "First Floor": IMG("photo-1503387837-b154d5074bd2", 1200),
      "Rooftop": IMG("photo-1502005229762-cf1b2da7c5d6", 1200),
    },
  },
  {
    id: "riverstone-villa",
    name: "Riverstone Villa",
    location: "Jaipur, Rajasthan",
    area: "Vaishali Nagar",
    price: 19500000,
    priceLabel: "₹1.95 Cr",
    listingType: "buy",
    type: "Villa",
    beds: 3,
    baths: 3,
    sqft: 2450,
    yearBuilt: 2021,
    parking: 2,
    floors: 2,
    status: "Ready to Move",
    furnished: "Semi-Furnished",
    featured: false,
    amenities: ["Garden", "Covered Parking", "Security", "Terrace"],
    tags: ["garden", "parking", "security"],
    images: [
      IMG("photo-1605276374104-dee2a0ed3cd6"),
      IMG("photo-1583608205776-bfd35f0d9f83"),
      IMG("photo-1600566753190-17f0baa2a6c3"),
      IMG("photo-1600047509807-ba8f99d2cdde"),
      IMG("photo-1523217582562-09d0def993a6"),
    ],
    description:
      "A compact, well-proportioned villa in Vaishali Nagar built around a central light well that keeps every room naturally lit through the day. Riverstone Villa suits a young family looking for their first freehold home without compromising on garden space.",
    headline: "Small footprint, generous light.",
    agentId: "aarav-mehta",
    walkscore: { city: 14, school: 4, airport: 20 },
    floorPlans: {
      "Ground Floor": IMG("photo-1503387762-592deb58ef4e", 1200),
      "First Floor": IMG("photo-1503387837-b154d5074bd2", 1200),
      "Rooftop": IMG("photo-1502005229762-cf1b2da7c5d6", 1200),
    },
  },
  {
    id: "harbour-loft",
    name: "Harbour Loft",
    location: "Mumbai",
    area: "Worli",
    price: 165000,
    priceLabel: "₹1,65,000 / mo",
    listingType: "rent",
    type: "Apartment",
    beds: 2,
    baths: 2,
    sqft: 1450,
    yearBuilt: 2020,
    parking: 1,
    floors: 1,
    status: "Available Now",
    furnished: "Fully Furnished",
    featured: false,
    amenities: ["Gym", "Security", "Smart Home", "Covered Parking"],
    tags: ["gym", "security", "parking"],
    images: [
      IMG("photo-1502672260266-1c1ef2d93688"),
      IMG("photo-1560185008-a33f5c7b1844"),
      IMG("photo-1554995207-c18c203602cb"),
      IMG("photo-1502005229762-cf1b2da7c5d6"),
      IMG("photo-1493809842364-78817add7ffb"),
    ],
    description:
      "A converted mill-district loft in Worli with 11-foot ceilings and the original steel roof trusses left exposed. Harbour Loft is offered fully furnished for tenants who want a considered home from day one, not a blank shell.",
    headline: "Exposed steel, considered comfort.",
    agentId: "anaya-sharma",
    walkscore: { city: 4, school: 9, airport: 25 },
    floorPlans: {
      "Ground Floor": IMG("photo-1503387762-592deb58ef4e", 1200),
      "First Floor": IMG("photo-1503387837-b154d5074bd2", 1200),
      "Rooftop": IMG("photo-1502005229762-cf1b2da7c5d6", 1200),
    },
  },
  {
    id: "palm-court-3b",
    name: "Palm Court Residence 3B",
    location: "Goa",
    area: "Siolim",
    price: 95000,
    priceLabel: "₹95,000 / mo",
    listingType: "rent",
    type: "Villa",
    beds: 3,
    baths: 3,
    sqft: 2100,
    yearBuilt: 2023,
    parking: 2,
    floors: 2,
    status: "Available from Oct",
    furnished: "Fully Furnished",
    featured: false,
    amenities: ["Private Pool", "Garden", "Covered Parking", "Security"],
    tags: ["pool", "garden", "parking"],
    images: [
      IMG("photo-1600566752229-450a15c8b0f1"),
      IMG("photo-1600585154526-990dced4db0d"),
      IMG("photo-1616486338812-3dadae4b4ace"),
      IMG("photo-1560185127-6ed189bf02f4"),
      IMG("photo-1521782462922-e78d0a35b8de"),
    ],
    description:
      "One of eight private villas within Palm Court, offered on a seasonal or annual lease. Residence 3B has a shaded plunge pool and an outdoor kitchen built for long, unhurried evenings.",
    headline: "A season in Siolim, on your terms.",
    agentId: "mira-kapoor",
    walkscore: { city: 22, school: 14, airport: 40 },
    floorPlans: {
      "Ground Floor": IMG("photo-1503387762-592deb58ef4e", 1200),
      "First Floor": IMG("photo-1503387837-b154d5074bd2", 1200),
      "Rooftop": IMG("photo-1502005229762-cf1b2da7c5d6", 1200),
    },
  },
  {
    id: "aravalli-view",
    name: "Aravalli View",
    location: "Gurugram",
    area: "Sohna Road",
    price: 27500000,
    priceLabel: "₹2.75 Cr",
    listingType: "buy",
    type: "Apartment",
    beds: 3,
    baths: 3,
    sqft: 2100,
    yearBuilt: 2024,
    parking: 1,
    floors: 1,
    status: "Ready to Move",
    furnished: "Unfurnished",
    featured: false,
    amenities: ["Gym", "Security", "Covered Parking", "Terrace"],
    tags: ["gym", "security", "parking"],
    images: [
      IMG("photo-1600607688969-a5bfcd646154"),
      IMG("photo-1600566752355-35792bedcfea"),
      IMG("photo-1600210491892-03d54c0aaf87"),
      IMG("photo-1600121848594-d8644e57abab"),
      IMG("photo-1493809842364-78817add7ffb"),
    ],
    description:
      "A mid-rise apartment on Sohna Road with unobstructed views toward the Aravalli ridge. Aravalli View was fitted with double-glazed windows and a dedicated home-office nook, built with hybrid working families in mind.",
    headline: "The ridge, close enough to walk to.",
    agentId: "kabir-singh",
    walkscore: { city: 16, school: 10, airport: 24 },
    floorPlans: {
      "Ground Floor": IMG("photo-1503387762-592deb58ef4e", 1200),
      "First Floor": IMG("photo-1503387837-b154d5074bd2", 1200),
      "Rooftop": IMG("photo-1502005229762-cf1b2da7c5d6", 1200),
    },
  },
];

const NESTORA_AGENTS = [
  {
    id: "aarav-mehta",
    name: "Aarav Mehta",
    specialty: "Luxury Residential Specialist",
    city: "Jaipur",
    years: 11,
    sold: 142,
    portrait: "https://randomuser.me/api/portraits/men/32.jpg",
    bio: "Aarav grew up around Jaipur's old-city havelis and has spent the last decade helping families translate that same sense of craft into new-build homes across the Pink City's expanding suburbs. He is known for a slow, unhurried approach — clients often describe him as more architect-minded than salesman.",
    areas: ["Amber Hills", "Vaishali Nagar", "Malviya Nagar", "Civil Lines"],
    specialties: ["Villas", "Independent Houses", "Land Acquisition"],
  },
  {
    id: "anaya-sharma",
    name: "Anaya Sharma",
    specialty: "Mumbai Property Advisor",
    city: "Mumbai",
    years: 9,
    sold: 98,
    portrait: "https://randomuser.me/api/portraits/women/44.jpg",
    bio: "Anaya spent six years in architectural conservation before moving into real estate, and it shows in how she talks about buildings — structure first, price second. She specialises in Mumbai's western suburbs, with a particular focus on heritage-adjacent and redeveloped properties.",
    areas: ["Bandra West", "Worli", "Khar", "Prabhadevi"],
    specialties: ["Penthouses", "Sea-facing Apartments", "Redevelopment"],
  },
  {
    id: "kabir-singh",
    name: "Kabir Singh",
    specialty: "Gurugram Real Estate",
    city: "Gurugram",
    years: 7,
    sold: 76,
    portrait: "https://randomuser.me/api/portraits/men/65.jpg",
    bio: "Kabir has tracked Gurugram's Golf Course Road corridor since its first towers broke ground, and works closely with relocating executives who need a fast, well-informed introduction to the city's newer developments.",
    areas: ["Golf Course Road", "Sohna Road", "Dwarka Expressway"],
    specialties: ["High-rise Apartments", "New Developments", "Corporate Relocation"],
  },
  {
    id: "mira-kapoor",
    name: "Mira Kapoor",
    specialty: "Goa Luxury Properties",
    city: "Goa",
    years: 13,
    sold: 165,
    portrait: "https://randomuser.me/api/portraits/women/68.jpg",
    bio: "Mira built her practice around Goa's village belts — Assagao, Siolim, Moira — long before they became sought-after. She works with both second-home buyers and investors, and is particular about matching a property's character to how a client actually intends to use it.",
    areas: ["Assagao", "Siolim", "Moira", "Anjuna"],
    specialties: ["Villas", "Vacation Homes", "Boutique Developments"],
  },
];

const NESTORA_DEVELOPMENTS = [
  {
    id: "nestora-heights",
    name: "Nestora Heights",
    location: "Gurugram",
    developer: "Marick Developers",
    startingPrice: "₹1.8 Cr",
    completion: "Dec 2027",
    units: "36 of 120 available",
    image: IMG("photo-1600585154340-be6161a56a0c"),
    description: "A twelve-storey residential tower on Dwarka Expressway with a rooftop clubhouse and landscaped podium gardens.",
  },
  {
    id: "palm-court",
    name: "Palm Court",
    location: "Goa",
    developer: "Coastline Estates",
    startingPrice: "₹2.4 Cr",
    completion: "Mar 2027",
    units: "9 of 18 available",
    image: IMG("photo-1600566752229-450a15c8b0f1"),
    description: "Eight private villas set within a shared palm grove, each with its own plunge pool and outdoor kitchen.",
  },
  {
    id: "the-ivory",
    name: "The Ivory",
    location: "Mumbai",
    developer: "Meridian Group",
    startingPrice: "₹3.9 Cr",
    completion: "Aug 2028",
    units: "54 of 90 available",
    image: IMG("photo-1600607687644-aac4c3eac7f4"),
    description: "A limestone-clad residential address in Bandra with a private members' lounge and sea-facing terraces.",
  },
];

const NESTORA_TESTIMONIALS = [
  {
    name: "Rhea & Vikram Anand",
    location: "Jaipur",
    property: "The Oak Residence",
    quote:
      "We viewed nine houses before Nestora showed us this one. Aarav understood almost immediately what we hadn't been able to describe to anyone else — that we wanted a house that felt lived-in on day one.",
  },
  {
    name: "Devansh Rao",
    location: "Goa",
    property: "Casa Verde",
    quote:
      "The process felt closer to working with an architect than a broker. Every question about the build quality was answered properly, not glossed over to close the sale faster.",
  },
  {
    name: "Priya Nair",
    location: "Mumbai",
    property: "The Terrace House",
    quote:
      "Anaya negotiated details most agents wouldn't think to raise — service lift access, terrace waterproofing warranties. Small things that mattered enormously six months in.",
  },
  {
    name: "Sameer & Lina Kapadia",
    location: "Gurugram",
    property: "Skyline 42",
    quote:
      "We were relocating from abroad with three weeks' notice. Kabir ran the entire shortlist, paperwork and final walkthrough over video call and had the keys ready when we landed.",
  },
];

const NESTORA_ARTICLES = [
  {
    title: "Where Jaipur's Luxury Residential Market Is Heading",
    category: "Market Insight",
    date: "Aug 2026",
    readTime: "6 min read",
    image: IMG("photo-1600585154340-be6161a56a0c"),
    excerpt: "New micro-markets along the Ajmer Road corridor are drawing a different kind of buyer than the old-city havelis ever did.",
  },
  {
    title: "5 Things to Look for Before Buying a Villa",
    category: "Buying Guide",
    date: "Jul 2026",
    readTime: "5 min read",
    image: IMG("photo-1613490493576-7fde63acd811"),
    excerpt: "Beyond square footage — the structural, legal and seasonal details that determine whether a villa ages well.",
  },
  {
    title: "Inside the Rise of Architectural Living",
    category: "Design",
    date: "Jun 2026",
    readTime: "8 min read",
    image: IMG("photo-1600566753086-00f18fb6b3ea"),
    excerpt: "A growing group of buyers are choosing architect-led homes over developer catalogues. We asked three of them why.",
  },
  {
    title: "How to Choose the Right Neighbourhood",
    category: "Buying Guide",
    date: "May 2026",
    readTime: "4 min read",
    image: IMG("photo-1600607687939-ce8a6c25118c"),
    excerpt: "Commute time is only the beginning. A framework for weighing schools, resale value and long-term character.",
  },
];
